## Example Data Collection code: 
#### Obtaining  WEATHER data for certain date intervals and future forecasts.
#### Just obtain API keys for yourself and get your own data for the datetime interval you desired.

## Geçmiş hava durumu

In [18]:
def get_historical_weather_data(api,city_name,city_id,start_date):
    import json
    import requests
    date_now=dt.datetime.now().strftime("%Y-%m-%d:%H")
    url="https://api.weatherbit.io/v2.0/history/hourly?city_id="+city_id+"&start_date="+start_date+"&end_date="+date_now+"&tz=local&key="+api
    response = requests.get(url)
    response.text
    d = json.loads(response.text)
    print(url) #take 2 hours more based on api location and Istanbul time
    datetime = [i["datetime"] for i in d["datas"]]
    humidity = [i["rh"] for i in d["datas"]]
    temp = [i["temp"] for i in d["datas"]]
    data=pd.DataFrame()
    data["Tarih"]=datetime
    data[city_name+"_temp"]=temp
    data[city_name+"_humidity"]=humidity
    return data.iloc[2:]  # take 2 forward based on api location and Istanbul time

In [20]:
api = "22d709aca2744ebeba3645b5e636edd1" #optain your own API KEY and use it within its lifetime
start_date="2019-01-01"
IstanbulAnadolu = get_historical_weather_data(api,"Istanbul_anadolu",'745044',start_date)
IstanbulAvrupa  = get_historical_weather_data(api,"Istanbul_avrupa",'745044',start_date)
Bursa           = get_historical_weather_data(api,"Bursa",'750269',start_date)
historical_weather_orj = pd.concat([IstanbulAnadolu,IstanbulAvrupa,Bursa],axis=1)

historical_weather=historical_weather_orj.copy()
historical_weather["Tarih"]=historical_weather.pop("Tarih").iloc[:,1]

historical_weather.Tarih=historical_weather.Tarih.apply(lambda x: pd.to_datetime(x[:10]+" "+str(x[-2:])+ ":00"))

https://api.weatherbit.io/v2.0/history/hourly?city_id=745044&start_date=2024-02-28&end_date=2024-04-19:16&tz=local&key=22d709aca2744ebeba3645b5e636edd1
https://api.weatherbit.io/v2.0/history/hourly?city_id=745044&start_date=2024-02-28&end_date=2024-04-19:16&tz=local&key=22d709aca2744ebeba3645b5e636edd1
https://api.weatherbit.io/v2.0/history/hourly?city_id=750269&start_date=2024-02-28&end_date=2024-04-19:16&tz=local&key=22d709aca2744ebeba3645b5e636edd1

In [21]:
historical_weather

,Istanbul_anadolu_temp,Istanbul_anadolu_humidity,Istanbul_avrupa_temp,Istanbul_avrupa_humidity,Bursa_temp,Bursa_humidity,Tarih
2,7.0,87,7.0,87,6.1,97,2024-02-27 23:00:00
3,7.1,84,7.1,84,5.3,98,2024-02-28 00:00:00
4,7.0,87,7.0,87,6.0,98,2024-02-28 01:00:00
5,7.0,87,7.0,87,4.8,100,2024-02-28 02:00:00
6,6.9,87,6.9,87,4.8,100,2024-02-28 03:00:00
...,...,...,...,...,...,...,...
1235,13.0,81,13.0,81,17.8,68,2024-04-19 08:00:00
1236,13.0,81,13.0,81,18.4,65,2024-04-19 09:00:00
1237,14.0,76,14.0,76,19.1,60,2024-04-19 10:00:00
1238,14.0,76,14.0,76,19.4,59,2024-04-19 11:00:00
1239,14.0,82,14.0,82,19.2,61,2024-04-19 12:00:00

### Gelecek Hava tahmini

In [37]:
import requests
import pandas as pd
import requests
import json
import numpy as np
import os
import sqlite3
def get_forecast_weather_data(api,city_name,city_id,forecast):
    url="https://api.weatherbit.io/v2.0/forecast/hourly?city_id="+city_id+"&key="+api+"&hours="+str(forecast+2)
    print(url) #take 2 hours more based on api location and Istanbul time
    response = requests.get(url)
    d = json.loads(response.text)
    datetime = [i["datetime"] for i in d["datas"]]
    humidity = [i["rh"] for i in d["datas"]]
    temp = [i["temp"] for i in d["datas"]]

    data=pd.DataFrame()
    data["Tarih"]=datetime
    data[city_name+"_temp"]=temp
    data[city_name+"_humidity"]=humidity
    return data.iloc[2:]  # take 2 forward based on api location and Istanbul time

In [38]:

api = "29385959e9174a32a43ef841beca77qw"

IstanbulAnadolu = get_forecast_weather_data(api,"Istanbul_anadolu",'745044',24)
IstanbulAvrupa  = get_forecast_weather_data(api,"Istanbul_avrupa",'745044',24)
Bursa           = get_forecast_weather_data(api,"Bursa",'750269',24)
forecast_weather_orj = pd.concat([IstanbulAnadolu,IstanbulAvrupa,Bursa],axis=1)

forecast_weather=forecast_weather_orj.copy()
forecast_weather["Tarih"]=forecast_weather.pop("Tarih").iloc[:,1]

forecast_weather.Tarih=forecast_weather.Tarih.apply(lambda x: pd.to_datetime(x[:10]+" "+str(x[-2:])+ ":00"))

https://api.weatherbit.io/v2.0/forecast/hourly?city_id=745044&key=29385959e9174a32a43ef841beca77bf&hours=26
https://api.weatherbit.io/v2.0/forecast/hourly?city_id=745044&key=29385959e9174a32a43ef841beca77bf&hours=26
https://api.weatherbit.io/v2.0/forecast/hourly?city_id=750269&key=29385959e9174a32a43ef841beca77bf&hours=26

In [39]:
historical_weather

,Istanbul_anadolu_temp,Istanbul_anadolu_humidity,Istanbul_avrupa_temp,Istanbul_avrupa_humidity,Bursa_temp,Bursa_humidity,Tarih
2,13.0,62,13.0,62,11.3,67,2023-02-27 23:00:00
3,12.0,71,12.0,71,10.8,68,2023-02-28 00:00:00
4,11.0,76,11.0,76,12.2,66,2023-02-28 01:00:00
5,10.0,81,10.0,81,13.7,62,2023-02-28 02:00:00
6,10.0,81,10.0,81,12.8,73,2023-02-28 03:00:00
...,...,...,...,...,...,...,...
4340,25.5,67,25.5,67,24.1,69,2023-08-27 17:00:00
4341,25.0,69,25.0,69,23.1,76,2023-08-27 18:00:00
4342,24.6,71,24.6,71,22.2,81,2023-08-27 19:00:00
4343,24.2,72,24.2,72,21.0,85,2023-08-27 20:00:00
4344,23.7,73,23.7,73,20.0,88,2023-08-27 21:00:00

In [40]:
forecast_weather

,Istanbul_anadolu_temp,Istanbul_anadolu_humidity,Istanbul_avrupa_temp,Istanbul_avrupa_humidity,Bursa_temp,Bursa_humidity,Tarih
2,24.2,71,24.2,71,21.9,80,2023-08-28 01:00:00
3,23.9,73,23.9,73,21.2,83,2023-08-28 02:00:00
4,23.5,75,23.5,75,20.9,85,2023-08-28 03:00:00
5,24.5,71,24.5,71,21.4,83,2023-08-28 04:00:00
6,25.4,68,25.4,68,22.6,79,2023-08-28 05:00:00
7,26.3,65,26.3,65,24.0,72,2023-08-28 06:00:00
8,26.9,61,26.9,61,25.7,65,2023-08-28 07:00:00
9,27.5,57,27.5,57,27.3,59,2023-08-28 08:00:00
10,28.1,54,28.1,54,28.7,54,2023-08-28 09:00:00
11,28.7,51,28.7,51,29.9,51,2023-08-28 10:00:00
12,29.4,48,29.4,48,30.7,49,2023-08-28 11:00:00
13,30.1,45,30.1,45,31.1,47,2023-08-28 12:00:00
14,29.8,46,29.8,46,31.3,47,2023-08-28 13:00:00
15,29.6,46,29.6,46,31.0,48,2023-08-28 14:00:00
16,29.3,47,29.3,47,30.4,49,2023-08-28 15:00:00
17,28.5,51,28.5,51,29.1,54,2023-08-28 16:00:00
18,27.7,56,27.7,56,27.6,58,2023-08-28 17:00:00
19,27.0,60,27.0,60,26.3,61,2023-08-28 18:00:00
20,26.5,64,26.5,64,25.3,66,2023-08-28 19:00:00
21,26.0,67,26.0,67,24.3,70,2023-08-28 20:00:00
22,25.5,71,25.5,71,23.4,73,2023-08-28 21:00:00
23,25.4,71,25.4,71,22.6,78,2023-08-28 22:00:00
24,25.1,72,25.1,72,21.9,80,2023-08-28 23:00:00
25,24.7,74,24.7,74,21.2,81,2023-08-29 00:00:00

In [41]:
final_data_ind = pd.merge(df_merged,historical_weather,how='inner',on='Tarih')

In [42]:
final_data_ind

,Tarih,Blok Eşleşme Miktarı,Saatlik Eşleşme Miktarı,Min. Alış Fiyatı,Max. Alış Fiyatı,Min. Satış Fiyatı,Max. Satış Fiyatı,Min. Eşleşme Fiyatı,Max. Eşleşme Fiyatı,Talep İşlem Hacmi,...,Dolar,Euro,Smfdolar,Smfeuro,Istanbul_anadolu_temp,Istanbul_anadolu_humidity,Istanbul_avrupa_temp,Istanbul_avrupa_humidity,Bursa_temp,Bursa_humidity
0,2023-02-28 00:00:00,945.7,1527.7,543.75,3255.00,543.75,3760.00,543.75,2941.68,41762838.50,...,18.857291,19.965118,139.198145,131.474302,12.0,71,12.0,71,10.8,68
1,2023-02-28 01:00:00,820.4,1101.3,0.00,2941.68,625.00,3760.00,625.00,2941.68,47542628.51,...,18.856539,19.964862,146.792576,138.643584,11.0,76,11.0,76,12.2,66
2,2023-02-28 02:00:00,715.9,837.3,0.00,3100.00,695.47,3759.87,695.47,3100.00,51686474.19,...,18.856300,19.964619,147.530000,139.340000,10.0,81,10.0,81,13.7,62
3,2023-02-28 03:00:00,716.5,750.6,0.00,3104.99,675.00,3759.99,675.00,2943.50,49710107.92,...,18.857312,19.965910,143.180000,135.230000,10.0,81,10.0,81,12.8,73
4,2023-02-28 04:00:00,931.7,930.4,0.00,3657.02,278.28,3759.82,278.28,3450.63,51158028.32,...,18.856349,19.965705,108.822763,102.776234,9.0,93,9.0,93,11.4,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,2023-08-27 15:00:00,2865.8,1394.6,0.01,2646.00,373.63,2781.00,373.63,1999.98,34144951.50,...,26.405782,28.489920,79.528037,73.710280,26.8,62,26.8,62,27.7,58
4336,2023-08-27 16:00:00,2418.9,1521.7,0.00,2781.00,0.10,2781.00,444.38,2170.60,41361365.65,...,26.404448,28.491121,76.425761,70.828381,26.0,64,26.0,64,25.7,65
4337,2023-08-27 17:00:00,2763.9,1404.2,0.00,2646.00,0.10,2781.00,376.22,2170.60,35049705.73,...,26.406688,28.491689,75.738390,70.195909,25.5,67,25.5,67,24.1,69
4338,2023-08-27 18:00:00,2215.9,1609.4,0.00,2781.00,0.10,2781.00,574.13,2751.93,53430156.37,...,26.406315,28.489905,87.100000,80.730000,25.0,69,25.0,69,23.1,76
4339,2023-08-27 19:00:00,2214.4,1818.0,0.00,2781.00,0.10,2781.00,684.13,2781.00,61336910.73,...,26.404842,28.488367,98.466789,91.265322,24.6,71,24.6,71,22.2,81

In [43]:
final_data_ind.to_csv("smfdb_with_weather.csv")